version: '3.7'
services:
  webapp:
    image: web
    build:
      context: .
      args:
        buildEnv: production
        buildPath:
    ports:
      - 80:80
  webapp-staging:
    image: web-staging
    build:
      context: .
      args:
        buildEnv: staging
        buildPath: /staging
    ports:
      - 801:80
